--Cau 1:

CREATE DATABASE BAITHI
GO
CREATE TABLE NHACUNGCAP(
MANCC CHAR(5) PRIMARY KEY,
TENNCC CHAR(50) NOT NULL,
QUOCGIA CHAR(30) NULL,
LOAINCC CHAR(20) NULL
);
CREATE TABLE DUOCPHAM(
MADP CHAR(4) PRIMARY KEY,
TENDP VARCHAR(50) NOT NULL,
LOAIDP VARCHAR(20) NOT NULL,
GIA MONEY NOT NULL
);
CREATE TABLE PHIEUNHAP(
SOPN CHAR(5) PRIMARY KEY,
NGNHAP SMALLDATETIME NULL,
MANCC CHAR(5) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
LOAINHAP VARCHAR(30) NULL
);
CREATE TABLE CTPN (
SOPN CHAR(5) NOT NULL FOREIGN KEY REFERENCES PHIEUNHAP(SOPN),
MADP CHAR(4) NOT NULL FOREIGN KEY REFERENCES DUOCPHAM(MADP),
SOLUONG INT,
CONSTRAINT PK_CTPN PRIMARY KEY(SOPN, MADP)
);
GO

--Cau 2:

INSERT INTO NHACUNGCAP VALUES('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen')
INSERT INTO NHACUNGCAP VALUES('NCC02', 'J. B. Pharmaceuticals', 'India', 'Vang lai')
INSERT INTO NHACUNGCAP VALUES('NCC03', 'Sapharco', 'Singapore', 'Vang lai')

INSERT INTO DUOCPHAM VALUES('DP01', 'Thuoc ho PH', 'Siro', 120000)
INSERT INTO DUOCPHAM VALUES('DP02', 'Zecuf Herbal CouchRemedy', 'Vien nen', 200000)
INSERT INTO DUOCPHAM VALUES('DP03', 'Cotrim', 'Vien sui', 80000)

INSERT INTO PHIEUNHAP VALUES('00001', '2017-11-22', 'NCC01', 'Noi dia')
INSERT INTO PHIEUNHAP VALUES('00002', '2017-12-04', 'NCC03', 'Nhap khau')
INSERT INTO PHIEUNHAP VALUES('00003', '2017-12-10', 'NCC02', 'Nhap khau')

INSERT INTO CTPN VALUES('00001', 'DP01', 100)
INSERT INTO CTPN VALUES('00001', 'DP02', 200)
INSERT INTO CTPN VALUES('00003', 'DP03', 543)
GO

--Cau 3:

ALTER TABLE DUOCPHAM ADD CONSTRAINT CK_GIA_LOAISP CHECK(((GIA>=100000) AND (LOAIDP='Siro')) OR LOAIDP NOT IN ('Siro'))
GO

--Cau 4:
CREATE TRIGGER trg_ins_upd_pn ON PHIEUNHAP
AFTER INSERT, UPDATE 
AS
BEGIN
IF EXISTS(
SELECT 1
FROM NHACUNGCAP NCC, INSERTED I
WHERE NCC.MANCC=I.MANCC AND NCC.QUOCGIA NOT IN ('Viet Nam') AND I.LOAINHAP NOT IN ('Nhap khau'))
BEGIN
PRINT 'LOI: LOAI NHAP KHONG HOP LE!'
ROLLBACK TRANSACTION
END
ELSE 
BEGIN
PRINT 'THEM/SUA THONG TIN THANH CONG!'
END
END
GO

--Cau 5:
SELECT SOPN
FROM PHIEUNHAP
WHERE YEAR(NGNHAP)=2017 AND MONTH(NGNHAP)=12
ORDER BY SOPN ASC
GO

--Cau 6:
SELECT MADP, TENDP
FROM DUOCPHAM
WHERE MADP IN(
SELECT MADP
FROM 
(SELECT MADP, SUM(SOLUONG) AS SLNHAP
FROM PHIEUNHAP PN INNER JOIN CTPN CT 
ON PN.SOPN=CT.SOPN
WHERE YEAR(NGNHAP)=2017 
GROUP BY MADP) A
WHERE SLNHAP>=ALL(SELECT SUM(SOLUONG) FROM PHIEUNHAP PN INNER JOIN CTPN CT 
ON PN.SOPN=CT.SOPN
WHERE YEAR(NGNHAP)=2017 
GROUP BY MADP)
)
GO


--Cau 7:
(SELECT DISTINCT C.MADP, D.TENDP
FROM CTPN C JOIN DUOCPHAM D ON D.MADP=C.MADP
JOIN PHIEUNHAP P ON C.SOPN=P.SOPN
JOIN NHACUNGCAP N ON N.MANCC=P.MANCC
WHERE N.LOAINCC='Thuong xuyen')
EXCEPT
(SELECT DISTINCT D.MADP, D.TENDP
FROM DUOCPHAM D INNER JOIN CTPN C ON D.MADP=C.MADP
INNER JOIN PHIEUNHAP P ON C.SOPN=P.SOPN
INNER JOIN NHACUNGCAP N ON N.MANCC=P.MANCC
WHERE LOAINCC='Vang lai')
GO

SELECT DISTINCT D.MADP, D.TENDP
FROM DUOCPHAM D
INNER JOIN CTPN C ON D.MADP = C.MADP
INNER JOIN PHIEUNHAP P ON C.SOPN = P.SOPN
INNER JOIN NHACUNGCAP N ON N.MANCC = P.MANCC
WHERE N.LOAINCC = 'Thuong xuyen'
  AND D.MADP NOT IN (
    SELECT C1.MADP
    FROM CTPN C1
    INNER JOIN PHIEUNHAP P1 ON C1.SOPN = P1.SOPN
    INNER JOIN NHACUNGCAP N1 ON N1.MANCC = P1.MANCC
    WHERE N1.LOAINCC = 'Vang lai'
  );


--Cau 8:
SELECT MANCC,TENNCC
FROM NHACUNGCAP NCC 
WHERE NOT EXISTS(
SELECT * 
FROM DUOCPHAM DP
WHERE GIA>100000 AND NOT EXISTS(
SELECT *
FROM CTPN CT JOIN PHIEUNHAP PN
ON CT.SOPN=PN.SOPN
WHERE YEAR(NGNHAP)=2017 AND PN.MANCC=NCC.MANCC AND CT.MADP=DP.MADP))
GO
